const speakerData = [{
        id: 0,
        name: 'Project name goes here...',
        image: 'images/laptop.png',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisiUt aliquip ex ea commodo consequat.  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi',
        tech: ['CSS', 'HTML', 'Bootstrap', 'Ruby'],
        live: 'https://gabrielcoder247.github.io/',
        source: 'https://github.com/gabrielcoder247/gabrielcoder247.github.io',
        btnLive: 'see live',
        btnSource: 'see source',
        btnImgGit: 'images/ic_github.png',
        btnImgTeal: 'images/ic_link_teal.png',
        seeThis: 'See this project',
    },
    {
        id: 1,
        name: 'Project name goes here...',
        image: 'images/screen.png',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisiUt aliquip ex ea commodo consequat.  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi',
        tech: ['CSS', 'HTML', 'Bootstrap', 'Ruby'],
        live: 'https://gabrielcoder247.github.io/',
        source: 'https://github.com/gabrielcoder247/gabrielcoder247.github.io',
        btnLive: 'see live',
        btnSource: 'see source',
        btnImgGit: 'images/ic_github.png',
        btnImgTeal: 'images/ic_link_teal.png',
        seeThis: 'See this project',
    },
    {
        id: 2,
        name: 'Project name goes here...',
        image: 'images/Rectangle-21devices.png',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisiUt aliquip ex ea commodo consequat.  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi',
        tech: ['CSS', 'HTML', 'Bootstrap', 'Ruby'],
        live: 'https://gabrielcoder247.github.io/',
        source: 'https://github.com/gabrielcoder247/gabrielcoder247.github.io',
        btnLive: 'see live',
        btnSource: 'see source',
        btnImgGit: 'images/ic_github.png',
        btnImgTeal: 'images/ic_link_teal.png',
        seeThis: 'See this project',
    },
    {
        id: 3,
        name: 'Project name goes here...',
        image: 'images/Rectangle47_1.png',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisiUt aliquip ex ea commodo consequat.  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi',
        tech: ['CSS', 'HTML', 'Bootstrap', 'Ruby'],
        live: 'https://gabrielcoder247.github.io/',
        source: 'https://github.com/gabrielcoder247/gabrielcoder247.github.io',
        btnLive: 'see live',
        btnSource: 'see source',
        btnImgGit: 'images/ic_github.png',
        btnImgTeal: 'images/ic_link_teal.png',
        seeThis: 'See this project',
    },
    {
        id: 4,
        name: 'Project name goes here...',
        image: 'images/Rectangle21device__4.png',
        description: 'This is project that i have done in microverse ',
        tech: ['CSS', 'HTML', 'Bootstrap', 'Ruby'],
        live: 'https://gabrielcoder247.github.io/',
        source: 'https://github.com/gabrielcoder247/gabrielcoder247.github.io',
        btnLive: 'see live',
        btnSource: 'see source',
        btnImgGit: 'images/ic_github.png',
        btnImgTeal: 'target="images/ic_link_teal.png',
        seeThis: 'See this project',
    },
    {
        id: 5,
        name: 'Project name goes here...',
        image: 'images/Rectangle21device__4.png',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisiUt aliquip ex ea commodo consequat.  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi',
        tech: ['CSS', 'HTML', 'Bootstrap', 'Ruby'],
        live: 'https://gabrielcoder247.github.io/',
        source: 'https://github.com/gabrielcoder247/gabrielcoder247.github.io',
        btnLive: 'see live',
        btnSource: 'see source',
        btnImgGit: 'images/ic_github.png',
        btnImgTeal: 'images/ic_link_teal.png',
        seeThis: 'See this project',
    },
];